title: "Avery Chong"
author: "Avery Chong"
description: "University of California, Santa Barbara"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "averyschong.github.io/github resume.pdf", title: "CV"}
  - {file: "portfolio.md", title: "Portfolio"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:averychong8@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/averyschong"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/avery-chong-318245208/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
